// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PR.Persistance;

#nullable disable

namespace PR.Persistance.Migrations
{
    [DbContext(typeof(PrDbContext))]
    partial class PrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PR.Domain.Oras.Oras", b =>
                {
                    b.Property<int>("CodOras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodOras"), 1L, 1);

                    b.Property<int>("CodTara")
                        .HasColumnType("int");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumarLocuitori")
                        .HasColumnType("int");

                    b.HasKey("CodOras");

                    b.HasIndex("CodTara");

                    b.ToTable("Oras", (string)null);
                });

            modelBuilder.Entity("PR.Domain.Tara.Tara", b =>
                {
                    b.Property<int>("CodTara")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodTara"), 1L, 1);

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CodTara");

                    b.ToTable("Tara", (string)null);
                });

            modelBuilder.Entity("PR.Domain.Oras.Oras", b =>
                {
                    b.HasOne("PR.Domain.Tara.Tara", "Tara")
                        .WithMany("Orase")
                        .HasForeignKey("CodTara")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tara");
                });

            modelBuilder.Entity("PR.Domain.Tara.Tara", b =>
                {
                    b.Navigation("Orase");
                });
#pragma warning restore 612, 618
        }
    }
}
